engines:
  # ... CONFIG CONTENT ...
  sonar-java:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      squid:S1118:
        enabled: false
# ... CONFIG CONTENT ...
  pmd:
    enabled: true